### ISSUE TITLE
the application was unable to start correctly (0xc00007b). click ok to close the application

### ISSUE THREAD

**Issue by zuils** [chrisbutner/ChessCoach#1]
Trying to run this in arena gui for windows, getting this error

**Comment by chrisbutner** [comment]
Are you on Windows or Linux?

To investigate:
1. Open a terminal/shell
2. Run the engine directly: `ChessCoachUci`
2. Run the command `go`

Hopefully the problem shows up.

It's most likely that Python isn't being found properly, TensorFlow isn't set up properly, or TensorFlow isn't finding GPUs/TPUs.

The [usage section of the README](https://github.com/chrisbutner/ChessCoach#usage) has some notes on working with Python and chess GUIs.

**Comment by zuils** [comment]
I figured out I didn't have desktop development for c++
