### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by gheinzl60** [chrisbutner/ChessCoach#4]
I am trying to install on Ubuntu 22.10

setup.sh:had to replace the following line
#sudo apt-get install -y --no-install-recommends qt5-default
 sudo apt-get install -y --no-install-recommends  qtbase5-dev qtchooser qt5-make qtbase5-dev-tools

then all fine until (problem: see end of text)

(venv) heinzl@Tower:~/Downloads/ChessCoach-main$ sudo ./build.sh release install
++ dirname ./build.sh
+ pushd .
/home/heinzl/Downloads/ChessCoach-main /home/heinzl/Downloads/ChessCoach-main
+ [[ 2 -eq 0 ]]
+ case $1 in
+ BUILD_TYPE=release
+ shift
+ BUILD_DIRECTORY=build/gcc/release
+ '[' '!' -f build/gcc/release/build.ninja ']'
+ ninja -C build/gcc/release install
ninja: Entering directory `build/gcc/release'
[1/11] Compiling C++ object libstockfish.a.p/cpp_Stockfish_syzygy_tbprobe.cpp.o
FAILED: libstockfish.a.p/cpp_Stockfish_syzygy_tbprobe.cpp.o 
c++ -Ilibstockfish.a.p -I. -I../../.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Werror -std=c++17 -O3 -march=native -O2 -DNDEBUG -flto -Wl,--start-group -lstdc++fs -Wl,--end-group -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx2 -mpopcnt -mbmi2 -DNO_PREFETCH -DUSE_POPCNT -DUSE_PEXT -DIS_64BIT -Wall -Wextra -Wpedantic -Wno-unknown-pragmas -Wno-sign-compare -fPIC -MD -MQ libstockfish.a.p/cpp_Stockfish_syzygy_tbprobe.cpp.o -MF libstockfish.a.p/cpp_Stockfish_syzygy_tbprobe.cpp.o.d -o libstockfish.a.p/cpp_Stockfish_syzygy_tbprobe.cpp.o -c ../../../cpp/Stockfish/syzygy/tbprobe.cpp
../../../cpp/Stockfish/syzygy/tbprobe.cpp: In member function ‘void {anonymous}::TBTables::clear()’:
../../../cpp/Stockfish/syzygy/tbprobe.cpp:451:15: error: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘{anonymous}::TBTables::Entry’ {aka ‘class std::tuple<long unsigned int, {anonymous}::TBTable<<unnamed>::WDL>*, {anonymous}::TBTable<<unnamed>::DTZ>*>’} with no trivial copy-assignment; use assignment instead [-Werror=class-memaccess]
  451 |         memset(hashTable, 0, sizeof(hashTable));
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/12/mutex:38,
                 from ../../../cpp/Stockfish/syzygy/tbprobe.cpp:30:
/usr/include/c++/12/tuple:609:11: note: ‘{anonymous}::TBTables::Entry’ {aka ‘class std::tuple<long unsigned int, {anonymous}::TBTable<<unnamed>::WDL>*, {anonymous}::TBTable<<unnamed>::DTZ>*>’} declared here
  609 |     class tuple : public _Tuple_impl<0, _Elements...>
      |           ^~~~~
../../../cpp/Stockfish/syzygy/tbprobe.cpp: In function ‘int Tablebases::probe_dtz(Position&, ProbeState*)’:
../../../cpp/Stockfish/syzygy/tbprobe.cpp:1462:22: error: loop variable ‘move’ of type ‘const Move&’ binds to a temporary constructed from type ‘const ExtMove’ [-Werror=range-loop-construct]
 1462 |     for (const Move& move : MoveList<LEGAL>(pos))
      |                      ^~~~
../../../cpp/Stockfish/syzygy/tbprobe.cpp:1462:22: note: use non-reference type ‘const Move’ to make the copy explicit or ‘const ExtMove&’ to prevent copying
../../../cpp/Stockfish/syzygy/tbprobe.cpp: In instantiation of ‘Tablebases::WDLScore {anonymous}::search(Position&, Tablebases::ProbeState*) [with bool CheckZeroingMoves = false]’:
../../../cpp/Stockfish/syzygy/tbprobe.cpp:1407:25:   required from here
../../../cpp/Stockfish/syzygy/tbprobe.cpp:1193:22: error: loop variable ‘move’ of type ‘const Move&’ binds to a temporary constructed from type ‘const ExtMove’ [-Werror=range-loop-construct]
 1193 |     for (const Move& move : moveList)
      |                      ^~~~
../../../cpp/Stockfish/syzygy/tbprobe.cpp:1193:22: note: use non-reference type ‘const Move’ to make the copy explicit or ‘const ExtMove&’ to prevent copying
../../../cpp/Stockfish/syzygy/tbprobe.cpp: In instantiation of ‘Tablebases::WDLScore {anonymous}::search(Position&, Tablebases::ProbeState*) [with bool CheckZeroingMoves = true]’:
../../../cpp/Stockfish/syzygy/tbprobe.cpp:1439:32:   required from here
../../../cpp/Stockfish/syzygy/tbprobe.cpp:1193:22: error: loop variable ‘move’ of type ‘const Move&’ binds to a temporary constructed from type ‘const ExtMove’ [-Werror=range-loop-construct]
../../../cpp/Stockfish/syzygy/tbprobe.cpp:1193:22: note: use non-reference type ‘const Move’ to make the copy explicit or ‘const ExtMove&’ to prevent copying
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.

**Comment by chrisbutner** [comment]
Should be fixed now for Ubuntu 22.04 - please try 22.10 again. Thanks!
