### ISSUE TITLE
How to apply the natural language comment feature onto a given PGN

### ISSUE THREAD

**Issue by gheinzl60** [chrisbutner/ChessCoach#5]
Dear Chris.
Having built and installed the software successfully which program is to be run and which actions are needed (e.g.: load PGN, analysis, export commented PGN) ?
Thanks

**Comment by chrisbutner** [comment]
First, make sure that you’ve installed TensorFlow and the right GPU or TPU components via these steps: https://github.com/chrisbutner/ChessCoach#installation

Download neural network weights using e.g. "scripts/download_install_data.sh" on Linux, following the Post-installation section: https://github.com/chrisbutner/ChessCoach#post-installation

Follow through the full Usage section to make sure that config.toml is set up properly for your GPU or TPU, and that the right Python environment is accessible: https://github.com/chrisbutner/ChessCoach#usage

The final steps depend on knowledge of the UCI protocol: https://www.shredderchess.com/download/div/uci.zip

Here’s an example:
1. Run “ChessCoachUci”
2. Type “ucinewgame” and Enter
3. Type “position startpos moves e2e4 e7e6 d2d4 d8g5” and Enter (move history is important for the neural network)
4. Type “isready” and Enter (wait for “readyok” to appear)
5. Type “comment” and Enter (wait for commentary to appear)

First example here: “This is a terrible blunder. I don't know what black was thinking, but it's a blunder.”

There’s currently no “commentate this PGN” functionality built in, but it can be scripted with the help of something like “python-chess” to read and write PGNs and SAN/UCI moves, or forked into the C++.
